# Generated by Django 3.2.8 on 2021-10-13 13:02

from django.db import migrations
import quiz_app.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_auto_20211013_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionorder',
            name='order',
            field=quiz_app.fields.OrderField(blank=True),
        ),
    ]
