# Generated by Django 3.2.8 on 2021-10-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_alter_quiz_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_questions',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.SmallIntegerField(default=0, help_text='Duration of the quiz [s]'),
        ),
    ]
