# Generated by Django 3.2.8 on 2021-10-30 17:10

from django.db import migrations, models
import django.db.models.deletion
import quiz_app.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_result_unique_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='quizzes',
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=quiz_app.fields.OrderField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quiz'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuestionOrder',
        ),
    ]
