# Generated by Django 3.2.8 on 2021-10-30 17:15

from django.db import migrations
import quiz_app.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_auto_20211030_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=quiz_app.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
